#!/bin/sh

PYTHON=`which python`
WHOAMI=`${PYTHON} -c 'import sys; import os; print os.path.abspath(sys.argv[1])' $0`

HOOKS=`dirname ${WHOAMI}`
DOTGIT=`dirname ${HOOKS}`
ROOT=`dirname ${DOTGIT}`

make metafiles concordances
